--주석 사용
--오라클에서 SQL문은 대소문자를 가리지 않는다.
--구문 마지막에 ;으로 마감한다.
--실행명령은 CTRL+ENTER

SELECT * FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES;

SELECT EMPLOYEE_ID, HIRE_DATE, SALARY FROM EMPLOYEES;

--NULL값 확인

SELECT EMPLOYEE_ID, SALARY, COMMISSION_PCT FROM EMPLOYEES;

--숫자 컬럼은 연산이 가능

SELECT EMPLOYEE_ID, SALARY, SALARY+SALARY*0.1 FROM EMPLOYEES;

--엘리어스 (컬럼명의 별칭)
SELECT EMPLOYEE_ID AS 사원아이디,
       FIRST_NAME AS 이름,
       LAST_NAME AS 성,
       SALARY+SALARY*0.1 AS 급여
       FROM EMPLOYEES;
       
--컬럼 연결 ||, 문자열의 표현 '', 문자열안에서 인용부호 '를 쓰고 싶다면 두번 쓰면 된다.
SELECT FIRST_NAME || LAST_NAME FROM EMPLOYEES;
SELECT FIRST_NAME || ' ' || LAST_NAME FROM EMPLOYEES;
SELECT FIRST_NAME || ' ' || LAST_NAME || '''S SALARY IS $' || SALARY AS 급여내역 FROM EMPLOYEES;

--행 중복 제거 DISTINCT
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT SALARY FROM EMPLOYEES;

--출력변호 (ROWNUM), 데이터위치 (ROWID)
SELECT ROWNUM, ROWID, EMPLOYEE_ID, FIRST_NAME FROM EMPLOYEES;

SELECT ROWNUM, FIRST_NAME FROM EMPLOYEES;