--데이터 행 제한 WHERE절

SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, JOB_ID, DEPARTMENT_ID FROM EMPLOYEES WHERE JOB_ID ='IT_PROG';

SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'Valli';
SELECT * FROM EMPLOYEES WHERE SALARY >= 15000;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 60;
SELECT * FROM EMPLOYEES WHERE HIRE_DATE >= '08/01/01'; -- 날짜 형식(년/월/일) 대소비교 가능
SELECT * FROM EMPLOYEES WHERE HIRE_DATE = '08/01/24';

--WHERE 연산자 (BETWEEN, IN, LIKE)

--BETWEEN

SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 10000 AND 20000;
SELECT * FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '05/01/01' AND '05/12/31';

--IN

SELECT * FROM EMPLOYEES WHERE MANAGER_ID IN (101, 102, 103);
SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('AD_ASST', 'FI_MGR', 'IT_PROG');

--LIKE (검색할 때 사용)

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE 'A%'; --A로 시작하는
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '05%'; --05로 시작하는
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '%15'; --15로 끝나는
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '%07%'; --07이 포함된
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '___07%'; -- _는 위치를 의미한다.


--SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT = NULL;

SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL; -- NULL값 검색
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL; -- NULL값이 아닌 값 검색

--AND, OR 조건 (AND가 OR보다 빠르다.)

SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' AND SALARY >= 6000;
SELECT * FROM EMPLOYEES WHERE SALARY >= 10000 AND SALARY <= 20000;

SELECT * FROM EMPLOYEES WHERE JOB_ID = 'AD_VP' OR SALARY >= 15000;

--우선순위를 결정하려면 ()를 이용하면 된다.
SELECT * FROM EMPLOYEES WHERE (JOB_ID = 'IT_PROG' OR JOB_ID = 'AD_VP') AND SALARY >= 6000;

--데이터 정렬 ORDER BY문

SELECT * FROM EMPLOYEES ORDER BY FIRST_NAME ASC;
SELECT * FROM EMPLOYEES ORDER BY HIRE_DATE ASC;
SELECT * FROM EMPLOYEES ORDER BY HIRE_DATE DESC;

SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('IT_PROG', 'AD_VP') ORDER BY SALARY ASC;

--급여가 5000 이상인 사람중에서 직원 아이디 기준으로 내림차순 정렬
SELECT * FROM EMPLOYEES WHERE SALARY >= 5000 ORDER BY EMPLOYEE_ID DESC;

--커미션이 NULL이 아닌 사람들 직원 아이디 기준으로 오름차순
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL ORDER BY EMPLOYEE_ID ASC;

--JOB_ID 기준 오름차순, 급여기준 내림차순 (여러 기준으로 정렬하려면 , 사용하면 된다.)
SELECT * FROM EMPLOYEES ORDER BY JOB_ID ASC, SALARY DESC;

--ORDER BY 문에서 AS를 이용해서 정렬이 가능하다.
SELECT FIRST_NAME || ' ' || LAST_NAME AS 이름,
       SALARY,
       SALARY * 12 AS 연봉
FROM EMPLOYEES
ORDER BY 연봉 DESC;